language: go

go:
  - "1.10"

install:
  #Installs Go Meta Linter (Golint and Go vet are also supported independently)
  - go get -u gopkg.in/alecthomas/gometalinter.v2
  - $GOPATH/bin/gometalinter.v2 --install
  - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.2.0.1873-linux.zip 
  - unzip sonar-scanner-cli-4.2.0.1873-linux.zip 
  - rm sonar-scanner-cli-4.2.0.1873-linux.zip 
  - mv sonar-scanner-4.2.0.1873-linux sonar-scanner 
addons:
  sonarcloud:
    organization: "rahmaboukhris"
    token: "e13369a1c4fb21ba40e43edc9d610d9c532b0440" # encrypted value of your token

script:
  # And then execute SonarCloud analysis which will run its own code analysis, and also reuse the linters' results
  - sonar-scanner/bin/sonar-scanner -Dsonar.organization=rahmaboukhris -Dsonar.projectKey=testmanual -Dsonar.projectName=testmanual

cache:
  directories:
  - '$HOME/.sonar/cache'
